_target_: src.pl_modules.mdrnn.MDRNNModel

#latents: 32
#actions: 3
#hiddens: 256
#gaussians: 5
#size: 64
#red_size: 64
#seq_len: 32

ASIZE: 1      # Action size: 1 is a scalar, n is an n-tuple.
LSIZE: 32     # Latent Size
RSIZE: 256    # Number of hidden units
RED_SIZE: 64  # 
SIZE: 64      # Image shape is SIZE x SIZE
SEQ_LEN: 32   # Sequence length
BSIZE: 32     # Batch size


vae_checkpoint_path: ${oc.env:PROJECT_ROOT}/checkpoints/vae/best.ckpt