optimizer:
  _target_: torch.optim.RMSprop
  lr: 0.001
  alpha: 0.9
  eps: 1e-08
  weight_decay: 0
  momentum: 0
  centered: False

use_lr_scheduler: True

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  mode: min
  factor: 0.5
  patience: 5
  threshold: 0.0001
  threshold_mode: rel
  cooldown: 0
  min_lr: 0
  eps: 1e-08
  verbose: False